name: Auto Approve PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve:
    if: github.actor == 'ADMETechDev'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve using GitHub CLI
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
