name: Auto Approve and Merge Codex PRs

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  auto-approve-and-merge:
    if: contains(github.event.pull_request.labels.*.name, 'codex-reviewed')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Auto-approve the PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Enabling auto-merge for PR #${{ github.event.pull_request.number }}"

          # Ensure the PR is mergeable
          gh pr merge ${{ github.event.pull_request.html_url }} --auto --merge
